import React, { createContext, useContext, useState, ReactNode } from 'react';

export type Language = 'en' | 'hi' | 'mr' | 'ta' | 'te' | 'bn' | 'gu' | 'kn' | 'ml' | 'pa';

interface LanguageContextType {
  language: Language;
  setLanguage: (lang: Language) => void;
  t: (key: string) => string;
}

const LanguageContext = createContext<LanguageContextType | undefined>(undefined);

export const useLanguage = () => {
  const context = useContext(LanguageContext);
  if (!context) {
    throw new Error('useLanguage must be used within LanguageProvider');
  }
  return context;
};

interface LanguageProviderProps {
  children: ReactNode;
}

export const LanguageProvider: React.FC<LanguageProviderProps> = ({ children }) => {
  const [language, setLanguage] = useState<Language>('en');

  const t = (key: string): string => {
    const translations = getTranslations(language);
    return translations[key] || key;
  };

  return (
    <LanguageContext.Provider value={{ language, setLanguage, t }}>
      {children}
    </LanguageContext.Provider>
  );
};

// Translation function
function getTranslations(lang: Language): Record<string, string> {
  const translations: Record<Language, Record<string, string>> = {
    en: {
      'app.title': 'CTC Tutor',
      'app.subtitle': 'Concept-to-Code Learning',
      'header.aiPowered': 'AI-Powered Learning',
      'tabs.concepts': 'Concept Explainer',
      'tabs.codeAnalysis': 'Code Analyzer',
      'tabs.studyMode': 'Study Mode',
      'concepts.title': 'Concept Explainer',
      'concepts.placeholder': 'Enter a concept to learn',
      'concepts.explain': 'Explain',
      'concepts.explaining': 'Explaining...',
      'code.title': 'Advanced Code Analyzer',
      'code.language': 'Programming Language',
      'code.yourCode': 'Your Code',
      'code.placeholder': 'Paste your code here for deep pedagogical analysis...',
      'code.analyze': 'Analyze Code',
      'code.analyzing': 'Analyzing...',
      'code.loadSample': 'Load Sample Code',
      'code.uploadImage': 'Upload Image',
      'study.title': 'Study Mode',
      'study.subtitle': 'Guided learning with Socratic questioning',
      'study.active': 'Active',
      'study.inactive': 'Inactive',
      'voice.listening': 'Listening...',
      'voice.speak': 'Speak',
      'voice.stop': 'Stop',
    },
    hi: {
      'app.title': 'सीटीसी ट्यूटर',
      'app.subtitle': 'अवधारणा-से-कोड सीखना',
      'header.aiPowered': 'एआई-संचालित शिक्षा',
      'tabs.concepts': 'अवधारणा व्याख्याकार',
      'tabs.codeAnalysis': 'कोड विश्लेषक',
      'tabs.studyMode': 'अध्ययन मोड',
      'concepts.title': 'अवधारणा व्याख्याकार',
      'concepts.placeholder': 'सीखने के लिए एक अवधारणा दर्ज करें',
      'concepts.explain': 'व्याख्या करें',
      'concepts.explaining': 'व्याख्या कर रहे हैं...',
      'code.title': 'उन्नत कोड विश्लेषक',
      'code.language': 'प्रोग्रामिंग भाषा',
      'code.yourCode': 'आपका कोड',
      'code.placeholder': 'गहन शैक्षणिक विश्लेषण के लिए अपना कोड यहां पेस्ट करें...',
      'code.analyze': 'कोड का विश्लेषण करें',
      'code.analyzing': 'विश्लेषण कर रहे हैं...',
      'code.loadSample': 'नमूना कोड लोड करें',
      'code.uploadImage': 'छवि अपलोड करें',
      'study.title': 'अध्ययन मोड',
      'study.subtitle': 'सुकराती प्रश्नोत्तरी के साथ निर्देशित शिक्षा',
      'study.active': 'सक्रिय',
      'study.inactive': 'निष्क्रिय',
      'voice.listening': 'सुन रहे हैं...',
      'voice.speak': 'बोलें',
      'voice.stop': 'रोकें',
    },
    mr: {
      'app.title': 'सीटीसी ट्यूटर',
      'app.subtitle': 'संकल्पना-ते-कोड शिक्षण',
      'header.aiPowered': 'एआय-चालित शिक्षण',
      'tabs.concepts': 'संकल्पना स्पष्टीकरण',
      'tabs.codeAnalysis': 'कोड विश्लेषक',
      'tabs.studyMode': 'अभ्यास मोड',
      'concepts.title': 'संकल्पना स्पष्टीकरण',
      'concepts.placeholder': 'शिकण्यासाठी संकल्पना प्रविष्ट करा',
      'concepts.explain': 'स्पष्ट करा',
      'concepts.explaining': 'स्पष्ट करत आहे...',
      'code.title': 'प्रगत कोड विश्लेषक',
      'code.language': 'प्रोग्रामिंग भाषा',
      'code.yourCode': 'तुमचा कोड',
      'code.placeholder': 'सखोल शैक्षणिक विश्लेषणासाठी तुमचा कोड येथे पेस्ट करा...',
      'code.analyze': 'कोड विश्लेषण करा',
      'code.analyzing': 'विश्लेषण करत आहे...',
      'code.loadSample': 'नमुना कोड लोड करा',
      'code.uploadImage': 'प्रतिमा अपलोड करा',
      'study.title': 'अभ्यास मोड',
      'study.subtitle': 'सॉक्रॅटिक प्रश्नोत्तरासह मार्गदर्शित शिक्षण',
      'study.active': 'सक्रिय',
      'study.inactive': 'निष्क्रिय',
      'voice.listening': 'ऐकत आहे...',
      'voice.speak': 'बोला',
      'voice.stop': 'थांबवा',
    },
    ta: {
      'app.title': 'CTC டியூட்டர்',
      'app.subtitle': 'கருத்து-முதல்-குறியீடு கற்றல்',
      'header.aiPowered': 'AI-இயங்கும் கற்றல்',
      'tabs.concepts': 'கருத்து விளக்கம்',
      'tabs.codeAnalysis': 'குறியீடு பகுப்பாய்வி',
      'tabs.studyMode': 'படிப்பு முறை',
      'concepts.title': 'கருத்து விளக்கம்',
      'concepts.placeholder': 'கற்க ஒரு கருத்தை உள்ளிடவும்',
      'concepts.explain': 'விளக்கவும்',
      'concepts.explaining': 'விளக்குகிறது...',
      'code.title': 'மேம்பட்ட குறியீடு பகுப்பாய்வி',
      'code.language': 'நிரலாக்க மொழி',
      'code.yourCode': 'உங்கள் குறியீடு',
      'code.placeholder': 'ஆழமான கற்பித்தல் பகுப்பாய்வுக்கு உங்கள் குறியீட்டை இங்கே ஒட்டவும்...',
      'code.analyze': 'குறியீட்டை பகுப்பாய்வு செய்',
      'code.analyzing': 'பகுப்பாய்வு செய்கிறது...',
      'code.loadSample': 'மாதிரி குறியீட்டை ஏற்றவும்',
      'code.uploadImage': 'படத்தை பதிவேற்றவும்',
      'study.title': 'படிப்பு முறை',
      'study.subtitle': 'சாக்ரடிக் கேள்விகளுடன் வழிகாட்டப்பட்ட கற்றல்',
      'study.active': 'செயலில்',
      'study.inactive': 'செயலற்றது',
      'voice.listening': 'கேட்கிறது...',
      'voice.speak': 'பேசு',
      'voice.stop': 'நிறுத்து',
    },
    te: {
      'app.title': 'CTC ట్యూటర్',
      'app.subtitle': 'కాన్సెప్ట్-టు-కోడ్ లెర్నింగ్',
      'header.aiPowered': 'AI-శక్తితో నేర్చుకోవడం',
      'tabs.concepts': 'కాన్సెప్ట్ వివరణ',
      'tabs.codeAnalysis': 'కోడ్ విశ్లేషణ',
      'tabs.studyMode': 'అధ్యయన మోడ్',
      'concepts.title': 'కాన్సెప్ట్ వివరణ',
      'concepts.placeholder': 'నేర్చుకోవడానికి ఒక కాన్సెప్ట్ నమోదు చేయండి',
      'concepts.explain': 'వివరించండి',
      'concepts.explaining': 'వివరిస్తోంది...',
      'code.title': 'అధునాతన కోడ్ విశ్లేషణ',
      'code.language': 'ప్రోగ్రామింగ్ భాష',
      'code.yourCode': 'మీ కోడ్',
      'code.placeholder': 'లోతైన విద్యా విశ్లేషణ కోసం మీ కోడ్‌ను ఇక్కడ పేస్ట్ చేయండి...',
      'code.analyze': 'కోడ్ విశ్లేషించండి',
      'code.analyzing': 'విశ్లేషిస్తోంది...',
      'code.loadSample': 'నమూనా కోడ్ లోడ్ చేయండి',
      'code.uploadImage': 'చిత్రాన్ని అప్‌లోడ్ చేయండి',
      'study.title': 'అధ్యయన మోడ్',
      'study.subtitle': 'సోక్రటిక్ ప్రశ్నలతో మార్గదర్శక అభ్యాసం',
      'study.active': 'క్రియాశీలం',
      'study.inactive': 'నిష్క్రియం',
      'voice.listening': 'వింటోంది...',
      'voice.speak': 'మాట్లాడు',
      'voice.stop': 'ఆపు',
    },
    bn: {
      'app.title': 'CTC টিউটর',
      'app.subtitle': 'ধারণা-থেকে-কোড শেখা',
      'header.aiPowered': 'AI-চালিত শিক্ষা',
      'tabs.concepts': 'ধারণা ব্যাখ্যাকারী',
      'tabs.codeAnalysis': 'কোড বিশ্লেষক',
      'tabs.studyMode': 'অধ্যয়ন মোড',
      'concepts.title': 'ধারণা ব্যাখ্যাকারী',
      'concepts.placeholder': 'শিখতে একটি ধারণা লিখুন',
      'concepts.explain': 'ব্যাখ্যা করুন',
      'concepts.explaining': 'ব্যাখ্যা করছে...',
      'code.title': 'উন্নত কোড বিশ্লেষক',
      'code.language': 'প্রোগ্রামিং ভাষা',
      'code.yourCode': 'আপনার কোড',
      'code.placeholder': 'গভীর শিক্ষাগত বিশ্লেষণের জন্য আপনার কোড এখানে পেস্ট করুন...',
      'code.analyze': 'কোড বিশ্লেষণ করুন',
      'code.analyzing': 'বিশ্লেষণ করছে...',
      'code.loadSample': 'নমুনা কোড লোড করুন',
      'code.uploadImage': 'ছবি আপলোড করুন',
      'study.title': 'অধ্যয়ন মোড',
      'study.subtitle': 'সক্রেটিক প্রশ্নোত্তর সহ নির্দেশিত শিক্ষা',
      'study.active': 'সক্রিয়',
      'study.inactive': 'নিষ্ক্রিয়',
      'voice.listening': 'শুনছে...',
      'voice.speak': 'বলুন',
      'voice.stop': 'থামুন',
    },
    gu: {
      'app.title': 'CTC ટ્યુટર',
      'app.subtitle': 'કોન્સેપ્ટ-ટુ-કોડ લર્નિંગ',
      'header.aiPowered': 'AI-સંચાલિત શિક્ષણ',
      'tabs.concepts': 'કોન્સેપ્ટ સમજૂતી',
      'tabs.codeAnalysis': 'કોડ વિશ્લેષક',
      'tabs.studyMode': 'અભ્યાસ મોડ',
      'concepts.title': 'કોન્સેપ્ટ સમજૂતી',
      'concepts.placeholder': 'શીખવા માટે એક કોન્સેપ્ટ દાખલ કરો',
      'concepts.explain': 'સમજાવો',
      'concepts.explaining': 'સમજાવી રહ્યું છે...',
      'code.title': 'અદ્યતન કોડ વિશ્લેષક',
      'code.language': 'પ્રોગ્રામિંગ ભાષા',
      'code.yourCode': 'તમારો કોડ',
      'code.placeholder': 'ઊંડા શૈક્ષણિક વિશ્લેષણ માટે તમારો કોડ અહીં પેસ્ટ કરો...',
      'code.analyze': 'કોડનું વિશ્લેષણ કરો',
      'code.analyzing': 'વિશ્લેષણ કરી રહ્યું છે...',
      'code.loadSample': 'નમૂના કોડ લોડ કરો',
      'code.uploadImage': 'છબી અપલોડ કરો',
      'study.title': 'અભ્યાસ મોડ',
      'study.subtitle': 'સોક્રેટિક પ્રશ્નો સાથે માર્ગદર્શિત શિક્ષણ',
      'study.active': 'સક્રિય',
      'study.inactive': 'નિષ્ક્રિય',
      'voice.listening': 'સાંભળી રહ્યું છે...',
      'voice.speak': 'બોલો',
      'voice.stop': 'બંધ કરો',
    },
    kn: {
      'app.title': 'CTC ಟ್ಯೂಟರ್',
      'app.subtitle': 'ಪರಿಕಲ್ಪನೆ-ಕೋಡ್ ಕಲಿಕೆ',
      'header.aiPowered': 'AI-ಚಾಲಿತ ಕಲಿಕೆ',
      'tabs.concepts': 'ಪರಿಕಲ್ಪನೆ ವಿವರಣೆ',
      'tabs.codeAnalysis': 'ಕೋಡ್ ವಿಶ್ಲೇಷಕ',
      'tabs.studyMode': 'ಅಧ್ಯಯನ ಮೋಡ್',
      'concepts.title': 'ಪರಿಕಲ್ಪನೆ ವಿವರಣೆ',
      'concepts.placeholder': 'ಕಲಿಯಲು ಪರಿಕಲ್ಪನೆಯನ್ನು ನಮೂದಿಸಿ',
      'concepts.explain': 'ವಿವರಿಸಿ',
      'concepts.explaining': 'ವಿವರಿಸುತ್ತಿದೆ...',
      'code.title': 'ಸುಧಾರಿತ ಕೋಡ್ ವಿಶ್ಲೇಷಕ',
      'code.language': 'ಪ್ರೋಗ್ರಾಮಿಂಗ್ ಭಾಷೆ',
      'code.yourCode': 'ನಿಮ್ಮ ಕೋಡ್',
      'code.placeholder': 'ಆಳವಾದ ಶೈಕ್ಷಣಿಕ ವಿಶ್ಲೇಷಣೆಗಾಗಿ ನಿಮ್ಮ ಕೋಡ್ ಅನ್ನು ಇಲ್ಲಿ ಅಂಟಿಸಿ...',
      'code.analyze': 'ಕೋಡ್ ವಿಶ್ಲೇಷಿಸಿ',
      'code.analyzing': 'ವಿಶ್ಲೇಷಿಸುತ್ತಿದೆ...',
      'code.loadSample': 'ಮಾದರಿ ಕೋಡ್ ಲೋಡ್ ಮಾಡಿ',
      'code.uploadImage': 'ಚಿತ್ರವನ್ನು ಅಪ್‌ಲೋಡ್ ಮಾಡಿ',
      'study.title': 'ಅಧ್ಯಯನ ಮೋಡ್',
      'study.subtitle': 'ಸಾಕ್ರಟಿಕ್ ಪ್ರಶ್ನೆಗಳೊಂದಿಗೆ ಮಾರ್ಗದರ್ಶಿ ಕಲಿಕೆ',
      'study.active': 'ಸಕ್ರಿಯ',
      'study.inactive': 'ನಿಷ್ಕ್ರಿಯ',
      'voice.listening': 'ಕೇಳುತ್ತಿದೆ...',
      'voice.speak': 'ಮಾತನಾಡಿ',
      'voice.stop': 'ನಿಲ್ಲಿಸಿ',
    },
    ml: {
      'app.title': 'CTC ട്യൂട്ടർ',
      'app.subtitle': 'ആശയം-മുതൽ-കോഡ് പഠനം',
      'header.aiPowered': 'AI-പ്രവർത്തിത പഠനം',
      'tabs.concepts': 'ആശയ വിശദീകരണം',
      'tabs.codeAnalysis': 'കോഡ് വിശകലനം',
      'tabs.studyMode': 'പഠന മോഡ്',
      'concepts.title': 'ആശയ വിശദീകരണം',
      'concepts.placeholder': 'പഠിക്കാൻ ഒരു ആശയം നൽകുക',
      'concepts.explain': 'വിശദീകരിക്കുക',
      'concepts.explaining': 'വിശദീകരിക്കുന്നു...',
      'code.title': 'വിപുലമായ കോഡ് വിശകലനം',
      'code.language': 'പ്രോഗ്രാമിംഗ് ഭാഷ',
      'code.yourCode': 'നിങ്ങളുടെ കോഡ്',
      'code.placeholder': 'ആഴത്തിലുള്ള വിദ്യാഭ്യാസ വിശകലനത്തിനായി നിങ്ങളുടെ കോഡ് ഇവിടെ ഒട്ടിക്കുക...',
      'code.analyze': 'കോഡ് വിശകലനം ചെയ്യുക',
      'code.analyzing': 'വിശകലനം ചെയ്യുന്നു...',
      'code.loadSample': 'സാമ്പിൾ കോഡ് ലോഡ് ചെയ്യുക',
      'code.uploadImage': 'ചിത്രം അപ്‌ലോഡ് ചെയ്യുക',
      'study.title': 'പഠന മോഡ്',
      'study.subtitle': 'സോക്രട്ടിക് ചോദ്യങ്ങളോടെ മാർഗനിർദേശ പഠനം',
      'study.active': 'സജീവം',
      'study.inactive': 'നിഷ്ക്രിയം',
      'voice.listening': 'കേൾക്കുന്നു...',
      'voice.speak': 'സംസാരിക്കുക',
      'voice.stop': 'നിർത്തുക',
    },
    pa: {
      'app.title': 'CTC ਟਿਊਟਰ',
      'app.subtitle': 'ਸੰਕਲਪ-ਤੋਂ-ਕੋਡ ਸਿੱਖਣਾ',
      'header.aiPowered': 'AI-ਸੰਚਾਲਿਤ ਸਿੱਖਣਾ',
      'tabs.concepts': 'ਸੰਕਲਪ ਵਿਆਖਿਆਕਾਰ',
      'tabs.codeAnalysis': 'ਕੋਡ ਵਿਸ਼ਲੇਸ਼ਕ',
      'tabs.studyMode': 'ਅਧਿਐਨ ਮੋਡ',
      'concepts.title': 'ਸੰਕਲਪ ਵਿਆਖਿਆਕਾਰ',
      'concepts.placeholder': 'ਸਿੱਖਣ ਲਈ ਇੱਕ ਸੰਕਲਪ ਦਾਖਲ ਕਰੋ',
      'concepts.explain': 'ਵਿਆਖਿਆ ਕਰੋ',
      'concepts.explaining': 'ਵਿਆਖਿਆ ਕਰ ਰਿਹਾ ਹੈ...',
      'code.title': 'ਉੱਨਤ ਕੋਡ ਵਿਸ਼ਲੇਸ਼ਕ',
      'code.language': 'ਪ੍ਰੋਗਰਾਮਿੰਗ ਭਾਸ਼ਾ',
      'code.yourCode': 'ਤੁਹਾਡਾ ਕੋਡ',
      'code.placeholder': 'ਡੂੰਘੇ ਸਿੱਖਿਆ ਵਿਸ਼ਲੇਸ਼ਣ ਲਈ ਆਪਣਾ ਕੋਡ ਇੱਥੇ ਪੇਸਟ ਕਰੋ...',
      'code.analyze': 'ਕੋਡ ਦਾ ਵਿਸ਼ਲੇਸ਼ਣ ਕਰੋ',
      'code.analyzing': 'ਵਿਸ਼ਲੇਸ਼ਣ ਕਰ ਰਿਹਾ ਹੈ...',
      'code.loadSample': 'ਨਮੂਨਾ ਕੋਡ ਲੋਡ ਕਰੋ',
      'code.uploadImage': 'ਚਿੱਤਰ ਅੱਪਲੋਡ ਕਰੋ',
      'study.title': 'ਅਧਿਐਨ ਮੋਡ',
      'study.subtitle': 'ਸੁਕਰਾਤੀ ਸਵਾਲਾਂ ਨਾਲ ਮਾਰਗਦਰਸ਼ਿਤ ਸਿੱਖਣਾ',
      'study.active': 'ਸਰਗਰਮ',
      'study.inactive': 'ਨਿਸ਼ਕਿਰਿਆ',
      'voice.listening': 'ਸੁਣ ਰਿਹਾ ਹੈ...',
      'voice.speak': 'ਬੋਲੋ',
      'voice.stop': 'ਰੋਕੋ',
    }
  };

  return translations[lang] || translations.en;
}
